<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});

Route::middleware('throttle:120,1')->prefix('/v1')->group(function () {

    Route::get('/punisher/di' ,function () {
        return response()->json([
            "negger",
            "(n)(i)(g)(g)(e)(r)",
            "_N_ _I_ _G_ _G_ _E_ _R_",
            "_N_I_G_G_E_R_",
            "n e g r o",
            "n eggas",
            "N i - G G ER",
            "n i 66e r",
            "n i b b a",
            "n i g a",
            "n i g g",
            "n i g g a",
            "N I G G A",
            "n i g g as",
            "n i g g e er",
            "fa/ggot",
            "n9igger",
            "n i g ggg er",
            "n i g gggggg er",
            "n i gg",
            "n i gg a",
            "N I GG AS",
            "n i gga",
            "n i gg-er",
            "n i q qer",
            "ffagggg",
            "n ig ga",
            "n igga",
            "libtard",
            "n a z i",
            "n a z is",
            "libtards",
            "n ii gga",
            "N IIIII GGGGG GGGG AAAAAA SSSSS",
            "n iq q e r",
            "N!993r",
            "n!gg@r",
            "fhaggot",
            "f-ggot",
            "n!gg3rs",
            "n!gga",
            "n!ggrs",
            "n(igga)",
            "n(igger)",
            "n*ggas",
            "n*gger",
            "n*ggers",
            "n*igga",
            "N,i,g,g,e,r",
            "N. IGGA",
            "n.1gga",
            "n.i.g.g.a",
            "n.i.g.g.e.r",
            "n.i.g.g.e.r.s.",
            "n.i.g.g@",
            "n/gger",
            "N;I;G;G;E;R",
            "n@gga",
            "n[i]gger",
            "N_I_G_G_E_R",
            "n - i - g - g - e - r",
            "n_IGGG__ER",
            "n|gger",
            "n|ig|g|e|r|s",
            "n|igger",
            "n+des",
            "N<IGER",
            "n11gers",
            "n1553r",
            "n1bba",
            "n1bbatoilet",
            "N1g*",
            "n1g*g3rrrr",
            "n1g*ga",
            "N1G*GER",
            "n1g3r",
            "n1ga",
            "n1ger",
            "N1GG",
            "n1gg23R",
            "n1gg33rs",
            "n1gg33rssss",
            "n1gg3r",
            "n1gg4",
            "n1gga",
            "n1ggar",
            "n1gger",
            "n1ggqa",
            "n1ggrs",
            "n1kcers",
            "n1lga",
            "n3b*ba",
            "n3ger",
            "ncde",
            "ndes",
            "ne!grows",
            "NEEEHGER",
            "neegörs",
            "neegrows",
            "neg*ga",
            "neg*gah",
            "neg*gas",
            "neg*grs",
            "negars",
            "nege r",
            "neger",
            "negers",
            "negor",
            "negro",
            "negroes",
            "Negros",
            "Nehger",
            "NGGA",
            "i hate white peopl",
            "i hate white people",
            "ngger",
            "nggers",
            "nggr",
            "nggrs",
            "flaggot",
            "ni g g a",
            "nvigger",
            "ni g ga",
            "i am a niger",
            "h i t l e r ",
            "u are retared",
            "n⛫i⛫g⛫g⛫",
            "ni ger",
            "ni gg a",
            "give me aids",
            "ni gg a er",
            "ni gg aaaa",
            "nI GG EGR",
            "u gay",
            "ni gg er",
            "ni gga",
            "ni ggas",
            "ni ggg a",
            "NI GGG AS",
            "ni gggg eeer",
            "ni gr",
            "NI GR",
            "n\uF802igger",
            "ni(ggas)",
            "Ni(ggers",
            "ni*gg",
            "ni*gga",
            "ni,,gqer",
            "ni...ga",
            "ni[[gerr",
            "NI___R",
            "ni1bbamoment",
            "NI33ER",
            "ni66er",
            "ni8ger",
            "ni99as",
            "How gay",
            "ni99er",
            "nxggxr",
            "ni99ers",
            "niaggaer",
            "rerard",
            "nibb a",
            "ur mom gae",
            "nibba",
            "fggt",
            "nick gers",
            "\/\\\/igguz",
            "nick gurr",
            "NICK GURRRRRRRRR",
            "nidger",
            "nigaaaaaa",
            "nigagaagagaga",
            "//!//iggas",
            "nigah",
            "nigar",
            "nigas",
            "Nigeas",
            "nigeers",
            "nigeger",
            "NIGEGR",
            "niGerKing",
            "nibas",
            "NI G GE ER",
            "niccers",
            "/\\/igger",
            "NIGG . ER",
            "niggha",
            "NIGGHRZ",
            "niggherz",
            "nieager",
            "i hate jews",
            "ｆｕｃｋｉｎｇ ｇａｙ",
            "ur big gay",
            "N⭍i\uE17Eg\uE17E\uE29Eg\uE17E\uE29Ee\u061Cr\uE29Es",
            "N*gga",
            "|\\| iggers",
            "yall are gey",
            "N!BBAS",
            "neggirs",
            "N_199er",
            "n1qqer",
            "you are aut i s tic",
            "joe niiiiiggggggggr",
            "re tard",
            "YOU BIG GAY",
            "nigtard",
            "nigerrrr",
            "ni⛫g⛫g⛫er",
            "nigerrrrrr",
            "nìgga",
            "UR GEAY",
            "r e t a r d",
            "nigerrr",
            "niiiiiiger",
            "niiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiger",
            "fwaggot",
            "is g4ay",
            "nιggas",
            "nιgger",
            "re tard",
            "yAlL aRe g@y",
            "f@ggot",
            "n\u05FCi\uE29Eg⭍g\uEFFEe\u05F6r\uE29E",
            "fa ggot",
            "nigerrrrrrrrr",
            "kank3r mongool",
            "n@gger",
            "nigerrrrrrrrrr",
            "n4ggers",
            "are gay",
            "nigers",
            "is gay",
            "NNNIIIIIIassGGGEEEEERRRRR",
            "i hate black people",
            "i hate black peopl",
            "niiiiger",
            "nigg",
            "NIIII*****GGGGAAAA",
            "ni gg wha",
            "ur ga.y",
            "n2gger",
            "ni@@er",
            "nigg a",
            "n1qqa",
            "u g a y",
            "heilll hittlerr",
            "ni g e r",
            "n¡gger",
            "Fa(ggots",
            "ret ard",
            "shut up gay",
            "f a g g ot",
            "fa gs",
            "is g a y",
            "nygher",
            "n1 ger",
            "f a g g o t",
            "you guys are all g a y",
            "ngerfgas",
            "u reatrd",
            "N/i/g/g/e/r",
            "n1 ggg",
            "Ni(gg)er",
            "Ni/g/ger",
            "i hate gays",
            "n¡gga",
            "niigea",
            "n_i_g_g_E_R",
            "f4ggot",
            "ur braindead",
            "N'IGG;ERS",
            "nigg@",
            "nIgg@",
            "nigg@r",
            "nigg@s",
            "nigg___ ers",
            "nigg____ ers",
            "nigg_a",
            "nigg2s",
            "nigg3r",
            "nigg4",
            "Nigg4a",
            "nigga",
            "n-i-g-g-a",
            "nígga",
            "niggder",
            "nigge",
            "nigge.r",
            "nigge_r",
            "nigge_Rs",
            "NIGGEA",
            "niggear",
            "niggeorjew",
            "nigg-er",
            "ni'gger",
            "ni-g-g-er",
            "n'igger",
            "n-i-g-g-e-r",
            "NI'GGERS",
            "nigges",
            "NIGGGGEEEE",
            "niggggeieier",
            "nigggggegr",
            "nigggggg a",
            "nigggggg3r",
            "nigggggggg3r",
            "nigggs",
            "NIGGHA",
            "niggier",
            "niggler",
            "niggmor",
            "niggo",
            "niggojew",
            "niggor",
            "niggorjew",
            "niggre",
            "NIGGRER",
            "NIGGRES",
            "niggrrrr",
            "niggrs",
            "niggs",
            "nigguh",
            "nigguh*",
            "niggur",
            "niggurs",
            "NIGGY",
            "nigha",
            "Nigha",
            "nigher",
            "nigqur",
            "nigr",
            "nigro",
            "NIGS",
            "nigsaer",
            "you're g a y",
            "nigur",
            "F*ggot",
            "nigver",
            "nigward",
            "niugga",
            "nihger",
            "niiga",
            "niigaaaa",
            "fagg",
            "so you gay",
            "you gay",
            "nGIGIGA",
            "retarted",
            "ngiga",
            "ni(*gg",
            "ｆａｇｇｏｔ",
            "ur gA y",
            "kneegas",
            "[n]igger",
            "niigers",
            "NIIIIGA",
            "niiiigers",
            "niiiiiigers",
            "nijjer",
            "nikers",
            "nikka",
            "NIOGER",
            "niqer",
            "niqqa",
            "niqqer",
            "njgegers",
            "njgget",
            "nlgga",
            "Nlgggger",
            "nligers",
            "NlIGGA",
            "nliggerboys",
            "nniger",
            "nogga",
            "nogger",
            "noggor",
            "nsgga",
            "migger",
            "nuiga",
            "nuigger",
            "nxiggers",
            "u r gay",
            "r e t a rd",
            "r e tard",
            "facggot",
            "nijger",
            "|\\|igger",
            "nygga",
            "DOWNIE",
            "fa ggots",
            "gaypixel",
            "ur g a y",
            "faaggot",
            "n#igger",
            "ni ggga",
            "nigg(a)",
            "faaaggggsss",
            "faaagggot",
            "fa gg ot",
            "hate asians",
            "i fuk black kneegas",
            "black slave",
            "hate bla(k guys",
            "I hat eblack people",
            "stupid asian",
            "diggah",
            "is g2y",
            "N i G 9 a",
            "faaagggottts",
            "hate black people",
            "kneeger",
            "hate blacks",
            "bnixggers",
            "nbigas",
            "ni ggg er",
            "faaaggs",
            "nigxga",
            "hate homo",
            "N I___GGER",
            "niaggers",
            "hate jews",
            "hitleer",
            "ni*gas",
            "njiggers",
            "ni BB a",
            "ni⛫gger",
            "= big gay",
            "faqqot",
            "gaynite",
            "ni88a",
            "NIGYGUER",
            "auutist",
            "n!qq@",
            "thats gay",
            "nigg e.r",
            "n13gg3r",
            "f ku gays",
            "N\uE17Ei\uE29Eg\uEFFE\uE17Eg\uEFFE\uE17Ee\u061Cr\uE29E\n",
            "i g g 3 r s",
            "void is gay",
            "Ni@@a",
            "fa gggg",
            "reta rd",
            "got big gay",
            "wigger",
            "Ⓡ℮Ⓣⓐℝd",
            "nbbas",
            "ni⛫⛫⛫gga",
            "ny0gga",
            "/\\/ IGGERS",
            "n!gg@",
            "sieg heil",
            "njgger",
            "nhiigger",
            "i say N u say igger",
            "n|qqa",
            "n iggga",
            "n0ggaer",
            "nig_ger",
            "ni⛫⛫gg⛫⛫er",
            "ur g@Y",
            "neeeegro",
            "nigiger",
            "neeeegro",
            "maggot",
            "n\uF802igg\uF802er",
            "n100gg003rs",
            "nİgga",
            "n**ger",
            "/\\/igga",
            "niba",
            "ｎｉｇｇｅｒ",
            "neigger",
            "die is gay",
            "nhigigier",
            "neggir",
            "fatfags",
            "this is gay",
            "you're g ay",
            "shut up queer",
            "h i t le r",
            "//Viggers",
            "leave = gay"
        ]);
    });


    Route::post('/sharex/create', function (Request $request) {

        $destinationPath = 'ss';

        $file = $request->file('sharex');
        $random_string = Str::random(5);

        $filename = $random_string.".".$file->extension();

        $file->move($destinationPath, $filename);

        if (DB::table('statistics')->where('name', 'screenshots')->get()){
            DB::table('statistics')->where('name', 'screenshots')->increment('amount');
        } else {
            DB::table('')->insert(
                ['name' => 'screenshots', 'amount' => 1]
            );
        }

        return url('/ss/'.$filename);

    })->name('api.sharex');

    Route::get('/sharex/stats', 'Api\PortfolioController@showScreenshots')->name('api.sharex.stats');

    /**
     * Route for the projects to show on the homepage.
     */
    Route::prefix('/portfolio')->group(function () {
        Route::resource('projects', 'Api\PortfolioController')->names([
            'index' => 'api.projects'
        ]);
        Route::post('contact', 'Api\PortfolioController@sendEmail')->name('api.portfolio.contact');

    });
});

